Updating configuration files.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3082,6 +3082,54 @@ else
   RANLIB="$ac_cv_prog_RANLIB"
 fi
 
+for ac_prog in gperf
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_XGPERF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$XGPERF"; then
+  ac_cv_prog_XGPERF="$XGPERF" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_XGPERF="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+XGPERF=$ac_cv_prog_XGPERF
+if test -n "$XGPERF"; then
+  echo "$as_me:$LINENO: result: $XGPERF" >&5
+echo "${ECHO_T}$XGPERF" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$XGPERF" && break
+done
+test -n "$XGPERF" || XGPERF="none"
+
+if test "$XGPERF" = "none"
+then
+	echo "*** Error:  No suitable gperf found. ***"
+	echo "    Please install the 'gperf' package."
+	exit 1
+fi
+
 
 
 echo "$as_me:$LINENO: checking for gzdopen in -lz" >&5
@@ -3157,53 +3205,6 @@ _ACEOF
 
 fi
 
-for ac_prog in gperf
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_XGPERF+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$XGPERF"; then
-  ac_cv_prog_XGPERF="$XGPERF" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_XGPERF="$ac_prog"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-XGPERF=$ac_cv_prog_XGPERF
-if test -n "$XGPERF"; then
-  echo "$as_me:$LINENO: result: $XGPERF" >&5
-echo "${ECHO_T}$XGPERF" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  test -n "$XGPERF" && break
-done
-test -n "$XGPERF" || XGPERF="none"
-
-if test "$XGPERF" = "none"
-then
-	echo "*** Error:  No suitable gperf found. ***"
-	echo "    Please install the 'gperf' package."
-	exit 1
-fi
 
 ## Tcl/Tk.
 
