Fixing lib Makefile and configuration file to compile the covered.vpi module via Makefile (instead of the iverilog-vpi) to give us more debug output.  Also fixed some compilation warnings with vpi.c and IV.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE RANLIB ac_ct_RANLIB XGPERF TCLTK_LIBS TCLTK_CPPFLAGS TCL_CONFIG TK_CONFIG CPP EGREP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS use_tcltk COVERED_BROWSER DEBUGDEF IVLIB VCSLIB VCSINC CVERLIB CVERINC LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE RANLIB ac_ct_RANLIB XGPERF TCLTK_LIBS TCLTK_CPPFLAGS TCL_CONFIG TK_CONFIG CPP EGREP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS use_tcltk COVERED_BROWSER DEBUGDEF IVLIB IVDIR VCSLIB VCSINC CVERLIB CVERINC LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -869,10 +869,8 @@ Optional Packages:
   --with-tk-config=TK_CONFIG
                           specify location of tkConfig.sh []
   --with-x                use the X Window System
-  --with-iv=IV_INCLUDE_DIR
-                          Create covered.vpi module for the Icarus Verilog
-                          simulator with the specified include directory
-                          []
+  --with-iv=IV_BASE_DIR   Create covered.vpi module for the Icarus Verilog
+                          simulator with the specified base directory []
   --with-vcs=VCS_INCLUDE_DIR
                           Create covered.vcs.so file for the VCS simulator
                           with the specified include directory []
@@ -5742,14 +5740,154 @@ if test "${with_iv+set}" = set; then
 elif test "${withval}" = yes; then
   want_iv=yes
 else
+  as_ac_Header=`echo "ac_cv_header_$withval/include/vpi_user.h" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $withval/include/vpi_user.h" >&5
+echo $ECHO_N "checking for $withval/include/vpi_user.h... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $withval/include/vpi_user.h usability" >&5
+echo $ECHO_N "checking $withval/include/vpi_user.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$withval/include/vpi_user.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $withval/include/vpi_user.h presence" >&5
+echo $ECHO_N "checking $withval/include/vpi_user.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$withval/include/vpi_user.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: $withval/include/vpi_user.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $withval/include/vpi_user.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $withval/include/vpi_user.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $withval/include/vpi_user.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: $withval/include/vpi_user.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $withval/include/vpi_user.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $withval/include/vpi_user.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $withval/include/vpi_user.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $withval/include/vpi_user.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $withval/include/vpi_user.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $withval/include/vpi_user.h" >&5
+echo $ECHO_N "checking for $withval/include/vpi_user.h... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
   want_iv=yes
-  iv_prefix="${withval}"
+     iv_prefix="${withval}"
+else
+  { { echo "$as_me:$LINENO: error: Invalid base directory specified in --with-iv" >&5
+echo "$as_me: error: Invalid base directory specified in --with-iv" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 fi
 else
   want_iv=no
 fi;
 if test "$want_iv" = yes; then
-  IVLIB='covered.vpi${EXEEXT}'
+  IVLIB='covered.vpi'
+
+  IVDIR="${iv_prefix}"
 
 fi
 
@@ -5762,7 +5900,6 @@ if test "${with_vcs+set}" = set; then
 elif test "${withval}" = yes; then
   want_vcs=yes
 else
-  want_vcs=yes
   as_ac_Header=`echo "ac_cv_header_$withval/vpi_user.h" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
   echo "$as_me:$LINENO: checking for $withval/vpi_user.h" >&5
@@ -5897,8 +6034,8 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
   want_vcs=yes
      vcs_prefix="${withval}"
 else
-  { { echo "$as_me:$LINENO: error: Invalid include path to --with-vcs" >&5
-echo "$as_me: error: Invalid include path to --with-vcs" >&2;}
+  { { echo "$as_me:$LINENO: error: Invalid include directory specified in --with-vcs" >&5
+echo "$as_me: error: Invalid include directory specified in --with-vcs" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -5908,7 +6045,7 @@ else
   want_vcs=no
 fi;
 if test "$want_vcs" = yes; then
-  VCSLIB='covered.vcs.so${EXEEXT}'
+  VCSLIB='covered.vcs.so'
 
   VCSINC="${vcs_prefix}"
 
@@ -5923,7 +6060,6 @@ if test "${with_cver+set}" = set; then
 elif test "${withval}" = yes; then
   want_cver=yes
 else
-  want_cver=yes
   as_ac_Header=`echo "ac_cv_header_$withval/vpi_user.h" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
   echo "$as_me:$LINENO: checking for $withval/vpi_user.h" >&5
@@ -6055,10 +6191,11 @@ echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
 
 fi
 if test `eval echo '${'$as_ac_Header'}'` = yes; then
-  cver_prefix="${withval}"
+  want_cver=yes
+     cver_prefix="${withval}"
 else
-  { { echo "$as_me:$LINENO: error: Invalid include path to --with-cver" >&5
-echo "$as_me: error: Invalid include path to --with-cver" >&2;}
+  { { echo "$as_me:$LINENO: error: Invalid include directory specified in --with-cver" >&5
+echo "$as_me: error: Invalid include directory specified in --with-cver" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -6068,7 +6205,7 @@ else
   want_cver=no
 fi;
 if test "$want_cver" = yes; then
-  CVERLIB='covered.cver.so${EXEEXT}'
+  CVERLIB='covered.cver.so'
 
   CVERINC="${cver_prefix}"
 
@@ -9227,6 +9364,7 @@ s,@use_tcltk@,$use_tcltk,;t t
 s,@COVERED_BROWSER@,$COVERED_BROWSER,;t t
 s,@DEBUGDEF@,$DEBUGDEF,;t t
 s,@IVLIB@,$IVLIB,;t t
+s,@IVDIR@,$IVDIR,;t t
 s,@VCSLIB@,$VCSLIB,;t t
 s,@VCSINC@,$VCSINC,;t t
 s,@CVERLIB@,$CVERLIB,;t t
